{% set name = "slixmpp" %}
{% set version = "1.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75e3f0ad48555f7f5c9228e7066c1d4358b33d640b4fbe773ec34b03b7fae9a3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - pkg-config  # [not win]
  host:
    - cython  # [not win]
    - libidn11  # [not win]
    - pip
    - python
  run:
    - aiodns >=1.0
    - libidn11  # [not win]
    - pyasn1
    - pyasn1-modules
    - python

test:
  imports:
    - slixmpp

about:
  home: https://slixmpp.readthedocs.io/
  doc_url: https://slixmpp.readthedocs.io/
  dev_url: https://lab.louiz.org/poezio/slixmpp
  summary: Slixmpp is an elegant Python library for XMPP (aka Jabber).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
