{% set name = "slixmpp" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60afcaa7c95a0fb9e7f1159cb70464a5558806d7abae29cd31e3fc883f9b8b0b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - pkg-config  # [not win]
  host:
    - cython  # [not win]
    - libidn11  # [not win]
    - pip
    - python
    - setuptools
  run:
    - aiodns >=1.0
    - libidn11  # [not win]
    - pyasn1
    - pyasn1-modules
    - python

test:
  imports:
    - slixmpp

about:
  home: https://slixmpp.readthedocs.io/
  doc_url: https://slixmpp.readthedocs.io/
  dev_url: https://lab.louiz.org/poezio/slixmpp
  summary: Slixmpp is an elegant Python library for XMPP (aka Jabber).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
